# Generated by Django 4.1.2 on 2022-11-11 11:00

from django.db import migrations, models
import validators.users


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(max_length=3, null=True, validators=[validators.users.check_age]),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
