# Generated by Django 4.1.2 on 2022-10-20 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=49)),
                ('author', models.CharField(max_length=30)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=5000, null=True)),
                ('address', models.CharField(max_length=50)),
                ('is_published', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.category')),
            ],
        ),
    ]
